# Generated by Django 2.1.5 on 2023-02-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientid', models.CharField(max_length=100)),
                ('patientname', models.CharField(max_length=100)),
                ('pre_disease', models.CharField(max_length=100)),
                ('doctorid', models.CharField(max_length=100)),
                ('symptoms', models.CharField(max_length=1000)),
                ('pre_doctor', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('appointdate', models.DateField(blank=True, null=True)),
                ('appointmentstatus', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PatientLogin',
            fields=[
                ('patientid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('secquestion', models.CharField(max_length=200)),
                ('secanswer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PatientRegistration',
            fields=[
                ('patientid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('patientname', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('extranumber', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientid', models.CharField(max_length=100)),
                ('doctorid', models.CharField(max_length=100)),
                ('star', models.FloatField()),
            ],
        ),
    ]
