# Generated by Django 2.1.5 on 2023-02-23 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_auto_20230223_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorregistration',
            old_name='education',
            new_name='gender',
        ),
    ]
