# Generated by Django 2.1.5 on 2023-02-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_auto_20230223_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorregistration',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
